name: artefact_challenge

on: push

#setup global env variables 
env:
  first_name: Adam
  last_name: Kowalski
  artifact_name: test_data

jobs:
  create_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: checkout action
        uses: actions/checkout@v2
      - name: make directory
        run: mkdir data
      - name: create a file
        run: echo "Hello ${{ env.first_name }} ${{ env.last_name }}" > "data/${{ env.artifact_name }}.txt" 
      - name: Artifact create and upload
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: "data/${{ env.artifact_name }}.txt" 
            
